apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
spec:
  selector:
    matchLabels:
      app: benchmark
  replicas: 1
  template:
    metadata:
      labels:
        app: benchmark
      namespace: aea-research
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: agent
        effect: NoSchedule
      nodeSelector:
        # type: agent-test
        kubernetes.io/os: linux
      initContainers:
      - name: python
        image: python:3.10-buster
        command: ['sh', '-c', 'bash /app/run_from_branch.sh | tee /data/index.html']
        volumeMounts:
        - name: benchmark-data
          mountPath: /data
        - name: benchmark-script
          mountPath: /app

      containers:
      - name: benchmark
        image: nginx:1.18.0
        volumeMounts:
        - name: benchmark-data
          mountPath: /usr/share/nginx/html
        - name: benchmark-script
          mountPath: /app

      volumes:
      - name: benchmark-data
        persistentVolumeClaim:
          claimName: benchmark-vol
      - name: benchmark-script
        persistentVolumeClaim:
          claimName: benchmark-scripts-vol

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-scripts-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
