agent_name: my_first_aea
author: fetchai
version: 0.27.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=2.0.0, <3.0.0'
fingerprint:
  README.md: bafybeib3kmhqz4qswa223lj3xkoejy26z6nm6uwv4ms6wkcsvu2jyxmfjy
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0:bafybeicrtlv4mvokl2o73bou4qey443vl6yclhh57v6il2iqt6ozjc4x34
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeifgerpr2pyffg2uxit6nettwoo2lhg2eqrdckjxl426pw2xipss4u
- fetchai/state_update:1.0.0:bafybeiglghpv27q766jilokbwolmyngztbftblrvaqfvqvxhxxhbbaboaq
- open_aea/signing:1.0.0:bafybeibovz6ixe636jsvel3etkcik33nl6sqj6pwutkykcwsukyrsgegmy
skills:
- fetchai/echo:0.19.0:bafybeicw5y7md7g4ujy7f2b4737pas4oa23266ujvzx7ome3qdkfi4cdoi
default_connection: fetchai/stub:0.21.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <3.0.0,>=2.0.0
