agent_name: my_first_aea
author: fetchai
version: 0.27.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=2.0.0, <3.0.0'
fingerprint:
  README.md: bafybeib3kmhqz4qswa223lj3xkoejy26z6nm6uwv4ms6wkcsvu2jyxmfjy
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0:bafybeicz7xjlohxsh7wxduipowreldqdhyri6l2jfggvgdbmkryq7y72dm
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeifipcrdiu27t5vg3zgvqc4dpcspskhtq4iqyugg5ktumf7ca7w46q
- fetchai/state_update:1.0.0:bafybeielfqxpupon2ue7oqrvx26pfdqpusi73fitvrq4g376d5gyb66ku4
- open_aea/signing:1.0.0:bafybeidx5kukmszm4dkabob6jciifiz6t7exvrrxl4b7y76kyd2rn2if74
skills:
- fetchai/echo:0.19.0:bafybeic7uhja6teqqhftxsc2mlkccodbpfeundzvewklm4kgdx6s57s7fe
default_connection: fetchai/stub:0.21.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <3.0.0,>=2.0.0
