agent_name: gym_aea
author: fetchai
version: 0.25.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=2.0.0, <3.0.0'
fingerprint:
  README.md: bafybeiezqjvhn3izsyoongmzc7glpdv233rmzzs6gimpspzw3cwx7ebysy
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.19.0:bafybeifgqsxvkfa66fgibyqyfrgb5dm2vpgovruazue7gdwbeejhsnl2um
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeih4zgjm7ifmovpzuwdobwb2kotvvr4gx3suwbn5j5z3pau4sioaou
- fetchai/gym:1.0.0:bafybeigq6gzu2fomjbouiagxfredcv4hlzkfuzewxnjvn5xyqhe5fed6mm
- fetchai/state_update:1.0.0:bafybeidwosqpgupk7dylhzbwpyoj2bg6poajgjijjg5l5qh5d76slpgx64
- open_aea/signing:1.0.0:bafybeifsjmldwyki3beqyvdt5lzenrg6wyrqaar5plc5rpnvtc4zlentye
skills:
- fetchai/gym:0.20.0:bafybeibyp3qnxzmgw3iiu3hz7xzisrlocvdts3qh662pun23no7tt6olq4
default_connection: fetchai/gym:0.19.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <3.0.0,>=2.0.0
