agent_name: gym_aea
author: fetchai
version: 0.25.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=2.0.0, <3.0.0'
fingerprint:
  README.md: bafybeiezqjvhn3izsyoongmzc7glpdv233rmzzs6gimpspzw3cwx7ebysy
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.19.0:bafybeigwjk6py6qig3vdgtd5seaq63pmqx63bcpkx7vjcvrheuwkf55sjq
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeifipcrdiu27t5vg3zgvqc4dpcspskhtq4iqyugg5ktumf7ca7w46q
- fetchai/gym:1.0.0:bafybeibx2w7krm42qpojcn3yeoapk4glvf43ft7phhbadh7utfzvenzouy
- fetchai/state_update:1.0.0:bafybeielfqxpupon2ue7oqrvx26pfdqpusi73fitvrq4g376d5gyb66ku4
- open_aea/signing:1.0.0:bafybeidx5kukmszm4dkabob6jciifiz6t7exvrrxl4b7y76kyd2rn2if74
skills:
- fetchai/gym:0.20.0:bafybeidy6zqjf4bj7qosc54iko767enxbclmkv66v5ipsvldxslvkwwdym
default_connection: fetchai/gym:0.19.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <3.0.0,>=2.0.0
