version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/packages/valory/connections/p2p_libp2p/libp2p_node"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "gomod"
    directory: "/libs/go/aealite"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "gomod"
    directory: "/libs/go/aea_end2end"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "gomod"
    directory: "/libs/go/aealite_agent_example"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
