# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: register.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eregister.proto\x12\x1a\x61\x65\x61.valory.register.v0_1_0"\xa3\x06\n\x0fRegisterMessage\x12O\n\x05\x65rror\x18\x05 \x01(\x0b\x32>.aea.valory.register.v0_1_0.RegisterMessage.Error_PerformativeH\x00\x12U\n\x08register\x18\x06 \x01(\x0b\x32\x41.aea.valory.register.v0_1_0.RegisterMessage.Register_PerformativeH\x00\x12S\n\x07success\x18\x07 \x01(\x0b\x32@.aea.valory.register.v0_1_0.RegisterMessage.Success_PerformativeH\x00\x1a\x9f\x01\n\x15Register_Performative\x12Y\n\x04info\x18\x01 \x03(\x0b\x32K.aea.valory.register.v0_1_0.RegisterMessage.Register_Performative.InfoEntry\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x9d\x01\n\x14Success_Performative\x12X\n\x04info\x18\x01 \x03(\x0b\x32J.aea.valory.register.v0_1_0.RegisterMessage.Success_Performative.InfoEntry\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\xc0\x01\n\x12\x45rror_Performative\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x11\n\terror_msg\x18\x02 \x01(\t\x12V\n\x04info\x18\x03 \x03(\x0b\x32H.aea.valory.register.v0_1_0.RegisterMessage.Error_Performative.InfoEntry\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0e\n\x0cperformativeb\x06proto3'
)


_REGISTERMESSAGE = DESCRIPTOR.message_types_by_name["RegisterMessage"]
_REGISTERMESSAGE_REGISTER_PERFORMATIVE = _REGISTERMESSAGE.nested_types_by_name[
    "Register_Performative"
]
_REGISTERMESSAGE_REGISTER_PERFORMATIVE_INFOENTRY = _REGISTERMESSAGE_REGISTER_PERFORMATIVE.nested_types_by_name[
    "InfoEntry"
]
_REGISTERMESSAGE_SUCCESS_PERFORMATIVE = _REGISTERMESSAGE.nested_types_by_name[
    "Success_Performative"
]
_REGISTERMESSAGE_SUCCESS_PERFORMATIVE_INFOENTRY = _REGISTERMESSAGE_SUCCESS_PERFORMATIVE.nested_types_by_name[
    "InfoEntry"
]
_REGISTERMESSAGE_ERROR_PERFORMATIVE = _REGISTERMESSAGE.nested_types_by_name[
    "Error_Performative"
]
_REGISTERMESSAGE_ERROR_PERFORMATIVE_INFOENTRY = _REGISTERMESSAGE_ERROR_PERFORMATIVE.nested_types_by_name[
    "InfoEntry"
]
RegisterMessage = _reflection.GeneratedProtocolMessageType(
    "RegisterMessage",
    (_message.Message,),
    {
        "Register_Performative": _reflection.GeneratedProtocolMessageType(
            "Register_Performative",
            (_message.Message,),
            {
                "InfoEntry": _reflection.GeneratedProtocolMessageType(
                    "InfoEntry",
                    (_message.Message,),
                    {
                        "DESCRIPTOR": _REGISTERMESSAGE_REGISTER_PERFORMATIVE_INFOENTRY,
                        "__module__": "register_pb2"
                        # @@protoc_insertion_point(class_scope:aea.valory.register.v0_1_0.RegisterMessage.Register_Performative.InfoEntry)
                    },
                ),
                "DESCRIPTOR": _REGISTERMESSAGE_REGISTER_PERFORMATIVE,
                "__module__": "register_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.register.v0_1_0.RegisterMessage.Register_Performative)
            },
        ),
        "Success_Performative": _reflection.GeneratedProtocolMessageType(
            "Success_Performative",
            (_message.Message,),
            {
                "InfoEntry": _reflection.GeneratedProtocolMessageType(
                    "InfoEntry",
                    (_message.Message,),
                    {
                        "DESCRIPTOR": _REGISTERMESSAGE_SUCCESS_PERFORMATIVE_INFOENTRY,
                        "__module__": "register_pb2"
                        # @@protoc_insertion_point(class_scope:aea.valory.register.v0_1_0.RegisterMessage.Success_Performative.InfoEntry)
                    },
                ),
                "DESCRIPTOR": _REGISTERMESSAGE_SUCCESS_PERFORMATIVE,
                "__module__": "register_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.register.v0_1_0.RegisterMessage.Success_Performative)
            },
        ),
        "Error_Performative": _reflection.GeneratedProtocolMessageType(
            "Error_Performative",
            (_message.Message,),
            {
                "InfoEntry": _reflection.GeneratedProtocolMessageType(
                    "InfoEntry",
                    (_message.Message,),
                    {
                        "DESCRIPTOR": _REGISTERMESSAGE_ERROR_PERFORMATIVE_INFOENTRY,
                        "__module__": "register_pb2"
                        # @@protoc_insertion_point(class_scope:aea.valory.register.v0_1_0.RegisterMessage.Error_Performative.InfoEntry)
                    },
                ),
                "DESCRIPTOR": _REGISTERMESSAGE_ERROR_PERFORMATIVE,
                "__module__": "register_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.register.v0_1_0.RegisterMessage.Error_Performative)
            },
        ),
        "DESCRIPTOR": _REGISTERMESSAGE,
        "__module__": "register_pb2"
        # @@protoc_insertion_point(class_scope:aea.valory.register.v0_1_0.RegisterMessage)
    },
)
_sym_db.RegisterMessage(RegisterMessage)
_sym_db.RegisterMessage(RegisterMessage.Register_Performative)
_sym_db.RegisterMessage(RegisterMessage.Register_Performative.InfoEntry)
_sym_db.RegisterMessage(RegisterMessage.Success_Performative)
_sym_db.RegisterMessage(RegisterMessage.Success_Performative.InfoEntry)
_sym_db.RegisterMessage(RegisterMessage.Error_Performative)
_sym_db.RegisterMessage(RegisterMessage.Error_Performative.InfoEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _REGISTERMESSAGE_REGISTER_PERFORMATIVE_INFOENTRY._options = None
    _REGISTERMESSAGE_REGISTER_PERFORMATIVE_INFOENTRY._serialized_options = b"8\001"
    _REGISTERMESSAGE_SUCCESS_PERFORMATIVE_INFOENTRY._options = None
    _REGISTERMESSAGE_SUCCESS_PERFORMATIVE_INFOENTRY._serialized_options = b"8\001"
    _REGISTERMESSAGE_ERROR_PERFORMATIVE_INFOENTRY._options = None
    _REGISTERMESSAGE_ERROR_PERFORMATIVE_INFOENTRY._serialized_options = b"8\001"
    _REGISTERMESSAGE._serialized_start = 47
    _REGISTERMESSAGE._serialized_end = 850
    _REGISTERMESSAGE_REGISTER_PERFORMATIVE._serialized_start = 320
    _REGISTERMESSAGE_REGISTER_PERFORMATIVE._serialized_end = 479
    _REGISTERMESSAGE_REGISTER_PERFORMATIVE_INFOENTRY._serialized_start = 436
    _REGISTERMESSAGE_REGISTER_PERFORMATIVE_INFOENTRY._serialized_end = 479
    _REGISTERMESSAGE_SUCCESS_PERFORMATIVE._serialized_start = 482
    _REGISTERMESSAGE_SUCCESS_PERFORMATIVE._serialized_end = 639
    _REGISTERMESSAGE_SUCCESS_PERFORMATIVE_INFOENTRY._serialized_start = 436
    _REGISTERMESSAGE_SUCCESS_PERFORMATIVE_INFOENTRY._serialized_end = 479
    _REGISTERMESSAGE_ERROR_PERFORMATIVE._serialized_start = 642
    _REGISTERMESSAGE_ERROR_PERFORMATIVE._serialized_end = 834
    _REGISTERMESSAGE_ERROR_PERFORMATIVE_INFOENTRY._serialized_start = 436
    _REGISTERMESSAGE_ERROR_PERFORMATIVE_INFOENTRY._serialized_end = 479
# @@protoc_insertion_point(module_scope)
