apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: open-aea
build:
  tagPolicy:
    envTemplate:
      template: "2.0.3"
  artifacts:
  - image: valory/open-aea-develop
    docker:
      dockerfile: develop-image/Dockerfile

  - image: valory/open-aea-user
    docker:
      dockerfile: user-image/Dockerfile

  - image: valory/open-aea-deploy
    docker:
      dockerfile: deploy-image/Dockerfile

profiles:
  - name: release
    build:
      tagPolicy:
        envTemplate:
          template: "2.0.3"
      artifacts:
      - image: valory/open-aea-docs
        docker:
          dockerfile: docs-image/Dockerfile
          noCache: true
      - image: valory/open-aea-develop
        docker:
          dockerfile: develop-image/Dockerfile
          noCache: true
      - image: valory/open-aea-user
        docker:
          dockerfile: user-image/Dockerfile
          noCache: true
      - image: valory/open-aea-deploy
        docker:
          dockerfile: deploy-image/Dockerfile
          noCache: true

  - name: release-latest
    build:
      tagPolicy:
        envTemplate:
          template: "latest"
      artifacts:
      - image: valory/open-aea-docs
        docker:
          dockerfile: docs-image/Dockerfile
      - image: valory/open-aea-develop
        docker:
          dockerfile: develop-image/Dockerfile
      - image: valory/open-aea-user
        docker:
          dockerfile: user-image/Dockerfile
      - image: valory/open-aea-deploy
        docker:
          dockerfile: deploy-image/Dockerfile
