agent_name: http_echo
author: open_aea
version: 0.1.0
license: Apache-2.0
description: Http echo agent blueprint configured with default variables.
aea_version: '>=2.0.0, <3.0.0'
fingerprint:
  README.md: bafybeide6e3netkj62dtt26l5os7opkbbaotgrzmxmxp4gvrhzx453hguu
fingerprint_ignore_patterns: []
connections:
- valory/http_server:0.22.0:bafybeihee232wlfd24inxdlommhdvunsqejwgnkukxdwshjrqsg5264rha
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeifgerpr2pyffg2uxit6nettwoo2lhg2eqrdckjxl426pw2xipss4u
- open_aea/signing:1.0.0:bafybeibovz6ixe636jsvel3etkcik33nl6sqj6pwutkykcwsukyrsgegmy
- valory/http:1.0.0:bafybeihoaje2mipaitmso2jfartdrqguof4qmly2tbeqebynnw2jfoagd4
skills:
- fetchai/http_echo:0.20.0:bafybeic2rnair5juussezxr4nuemy75fhiyijzq5c4jlpz5xbfljlzxaru
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/http_server:0.22.0
type: connection
config:
  host: ${HOST:str:localhost}
  port: ${PORT:int:5000}
  target_skill_id: ${TARGET_SKILL:str:fetchai/http_echo:0.20.0}
