# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#
#   Copyright 2026 Valory AG
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# ------------------------------------------------------------------------------

"""Tests for secp256k1 compressed public key validation."""

import pytest
from ecdsa import SECP256k1, SigningKey

from aea.helpers.secp256k1 import validate_secp256k1_compressed_pubkey


class TestValidKeys:
    """Tests with valid secp256k1 keys generated by the ecdsa library."""

    def test_generated_keys(self) -> None:
        """Test validation of freshly generated keys."""
        for _ in range(20):
            sk = SigningKey.generate(curve=SECP256k1)
            compressed = sk.get_verifying_key().to_string("compressed")
            # Should not raise
            validate_secp256k1_compressed_pubkey(compressed)

    def test_even_prefix(self) -> None:
        """Test key with 0x02 prefix (even y)."""
        key = bytes.fromhex(
            "025bb1b7fd08e741f1c6bf1d5ea508e4f47ddff51ac6a710b25657b6e69a43ffa5"
        )
        validate_secp256k1_compressed_pubkey(key)

    def test_odd_prefix(self) -> None:
        """Test key with 0x03 prefix (odd y)."""
        key = bytes.fromhex(
            "03fb9b7bb2d1e5a7a78e31decc5236300fc93e7c4abb84181757eeaaead95446a2"
        )
        validate_secp256k1_compressed_pubkey(key)


class TestInvalidKeys:
    """Tests with invalid inputs."""

    def test_wrong_length(self) -> None:
        """Test rejection of wrong-length input."""
        with pytest.raises(ValueError, match="33 bytes"):
            validate_secp256k1_compressed_pubkey(b"\x02" + b"\xab" * 31)

    def test_wrong_prefix(self) -> None:
        """Test rejection of invalid prefix byte."""
        with pytest.raises(ValueError, match="prefix"):
            validate_secp256k1_compressed_pubkey(b"\x04" + b"\xab" * 32)

    def test_zero_x(self) -> None:
        """Test rejection of x = 0 (not on curve: y² = 7 has no sqrt mod p)."""
        with pytest.raises(ValueError, match="not on.*curve"):
            validate_secp256k1_compressed_pubkey(b"\x02" + b"\x00" * 32)

    def test_x_not_on_curve(self) -> None:
        """Test rejection of x where y² has no square root."""
        # x = 5: y² = 125 + 7 = 132 has no square root mod p
        key = b"\x02" + (5).to_bytes(32, "big")
        with pytest.raises(ValueError, match="not on.*curve"):
            validate_secp256k1_compressed_pubkey(key)

    def test_empty_bytes(self) -> None:
        """Test rejection of empty input."""
        with pytest.raises(ValueError):
            validate_secp256k1_compressed_pubkey(b"")


class TestCrossValidation:
    """Cross-validate against the ecdsa library for 100% parity."""

    def test_all_generated_keys_match(self) -> None:
        """Test that our validator agrees with ecdsa on 50 random keys."""
        from ecdsa import VerifyingKey, curves

        for _ in range(50):
            sk = SigningKey.generate(curve=SECP256k1)
            compressed = sk.get_verifying_key().to_string("compressed")

            # Both should accept
            VerifyingKey._from_compressed(compressed, curves.SECP256k1)
            validate_secp256k1_compressed_pubkey(compressed)

    def test_known_invalid_keys_match(self) -> None:
        """Test that both validators reject the same invalid keys."""
        from ecdsa import VerifyingKey, curves, keys

        invalid_keys = [
            b"\x02" + b"\x00" * 32,
            b"\x02" + (2).to_bytes(32, "big"),
        ]
        for key in invalid_keys:
            ours_raises = False
            ecdsa_raises = False
            try:
                validate_secp256k1_compressed_pubkey(key)
            except ValueError:
                ours_raises = True
            try:
                VerifyingKey._from_compressed(key, curves.SECP256k1)
            except keys.MalformedPointError:
                ecdsa_raises = True
            assert (
                ours_raises == ecdsa_raises
            ), f"Mismatch for {key.hex()}: ours={ours_raises}, ecdsa={ecdsa_raises}"
