FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y                                                       \
       dialog                                                                \
       sudo                                                                  \
       apt-utils                                                             \
       build-essential                                                       \
       software-properties-common                                            \
       vim                                                                   \
       make                                                                  \
       git                                                                   \
       less                                                                  \
       curl                                                                  \
       wget                                                                  \
       zlib1g-dev                                                            \
       libssl-dev                                                            \
       libffi-dev                                                            \
       python3-venv                                                          \
       python3-pip                                                           \
       python3-dev


# This adds the 'default' user to sudoers with full privileges:
RUN HOME=/home/default &&                                                    \
    mkdir -p ${HOME} &&                                                      \
    GROUP_ID=1000 &&                                                         \
    USER_ID=1000 &&                                                          \
    groupadd -r default -f -g "$GROUP_ID" &&                                 \
    useradd -u "$USER_ID" -r -g default -d "$HOME" -s /sbin/nologin          \
    -c "Default Application User" default &&                                 \
    chown -R "$USER_ID:$GROUP_ID" ${HOME} &&                                 \
    usermod -a -G sudo default &&                                            \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers


# matplotlib build dependencies
RUN apt-get install -y                                                       \
       libxft-dev															 \
       libfreetype6											                 \
       libfreetype6-dev


ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN sudo apt-get install -y tox
RUN python3 -m pip install -U poetry==2.3.2

RUN sudo mkdir /build
WORKDIR /build
COPY . /build

RUN sudo make clean

RUN poetry install --all-extras --no-interaction

RUN python3 -m pip install -U open-aea-ledger-ethereum[all]

CMD ["/bin/bash"]
